import { useState } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import { stringify } from "querystring";

import CategoryList from "../components/elements/Categorylist";
import Header from "../components/elements/Header";
import LightBox from "../components/elements/LightBox";
import ServiceCard from "../components/views/ServiceCard";
import { Category } from "../data/category";
import { Service } from "../data/service";
import data from "../data/service.json";

const Home: NextPage = () => {
  const services: Category[] = data;
  const categories: string[] = [];
  services.forEach((serviceType) => categories.push(serviceType.category));
  const [show, setShow] = useState(false);
  return (
    <div>
      <Head>
        <title>FindIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header categories={categories} show={show} setShow={setShow} />
        <LightBox services={services} show={show} setShow={setShow} />

      </main>
    </div>
  );
};

export default Home;
